import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "../lib/utils";
import "./globals.css";
import Navbar from "../components/navbar";
import Providers from "../components/providers";
import 'react-loading-skeleton/dist/skeleton.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Providers>      
        <body className={cn(`min-h-screen font-sans antialiased`, geistSans.variable, geistMono.variable)}>
        <Navbar />
        {children}
        </body>
      </Providers>
    </html>
  );
}
